# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# Configuration
export EDITOR='nvim'
# Aliases
alias wclone='git clone -c "core.sshCommand=ssh -i ~/.ssh/work -F /dev/null"'
# Prompt
eval "$(starship init bash)"
