# ~/.bashrc
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# Configuration
export EDITOR='nvim'

## uv
export PATH="/home/rlegacy/.local/bin:$PATH"

## Prompt
eval "$(starship init bash)"

# Aliases
alias wclone='git clone -c "core.sshCommand=ssh -i ~/.ssh/work -F /dev/null"'
alias python='uv run python'
